@startuml exerciseClassDiagram

package "com.directi.training.ocp.exercise" {
    class ResourceAllocator {
        -INVALID_RESOURCE_ID: int
        +allocate(resourceType: ResourceType): int
        +free(resourceType: ResourceType, resourceId: int): void
        -markSpaceSlotFree(resourceId: int): void
        -markTimeSlotFree(resourceId: int): void
        -markSpaceSlotBusy(resourceId: int): void
        -findFreeSpaceSlot(): int
        -markTimeSlotBusy(resourceId: int): void
        -findFreeTimeSlot(): int
    }
    enum ResourceType {
        TIME_SLOT
        SPACE_SLOT
    }
'ResourceAllocator uses the ResourceType enumeration
    ResourceAllocator --> ResourceType
}

@enduml
